// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzchvsiivpsfitoxxhwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Y2h2c2lpdnBzZml0b3h4aHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTc4NzMsImV4cCI6MjA2OTE5Mzg3M30.ISI0rz_n7CnURHtjcbKYjYO1iKlD2eAD3CCe_JOHQp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});